# ******************************************************************************************************
# ************************************** 测试环境配置 ****************************************************
# ******************************************************************************************************

deploy-test-kefu:
  stage: deploy
  tags:
    - build
  only:
    - develop
  environment:
    name: testing
  script:
    - export PRODUCTION=false
    - docker-compose stop
    - docker-compose up -d --build