# ******************************************************************************************************
# ************************************** 生产环境配置 ****************************************************
# ******************************************************************************************************

deploy-test-kefu:
  stage: deploy
  tags:
    - build
  only:
    - develop
  environment:
    name: testing
  script:
    - export PRODUCTION=false
    - docker-compose stop
    - docker-compose up -d --build

# ******************************************************************************************************
# ************************************** 生产环境配置 ****************************************************
# ******************************************************************************************************

deploy-prod-kefu:
  stage: deploy
  tags:
  - release
  only:
  - master
  environment:
    name: production
  script:
    - export PRODUCTION=true
    - docker-compose stop
    - docker-compose up -d --build