before_script:
  - echo " CI is running... "
  - docker_image_version=latest

# ******************************************************************************************************
# ************************************** 生产环境配置 ****************************************************
# ******************************************************************************************************

deploy-test-kefu:
  stage: deploy
  tags:
    - build
  only:
    - develop
  environment:
    name: testing
  script:
    - docker-compose stop
    - docker-compose up -d --build

# ******************************************************************************************************
# ************************************** 生产环境配置 ****************************************************
# ******************************************************************************************************

deploy-prod-kefu:
  stage: deploy
  tags:
  - build
  only:
  - master
  environment:
    name: production
  script:
    - docker-compose stop
    - docker-compose up -d --build