version: '3'
services:
  ai:
    image: docker.jsjit.cn/ai/nlp:1.6
    ports:
      - 5000:5000
    networks:
      - customer_service
  kf_core:
    build: .
    image: docker.jsjit.cn/kefu/kefu-online:latest
    ports:
      - 20701:5000
    networks:
      - customer_service
    environment:
      PRODUCTION: ${PRODUCTION}
    depends_on:
      - ai
    volumes:
      - /opt/www:/www
      - /opt/upload:/upload

networks:
  customer_service: